// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Daniel Tralamazza
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig, type Plugin, type ServerOptions } from 'vite';

/*
 * Development serving.
 *
 * By default the dev server binds to 127.0.0.1 over plain HTTP: the only origin a
 * phone or another machine can reach is localhost, and localhost is a secure context,
 * so WebUSB works for whoever runs the browser on this machine.
 *
 * `LOGICWEB_LAN=1` (the `dev:lan` / `preview:lan` scripts) binds every interface so a
 * phone on the same Wi-Fi can open the page. WebUSB refuses to exist outside a secure
 * context, and a bare LAN IP over HTTP is not one, so LAN mode serves HTTPS from the
 * self-signed pair in certs/ (generated by `npm run cert`). The phone must accept the
 * certificate warning once; after that https://<lan-ip>:5173 is a secure context and
 * `navigator.usb` is present, so a logic analyser plugged into the phone (Android
 * Chrome, USB-C/OTG) is usable. Testing only the responsive layout needs no device.
 */
function lanServer(port: number): ServerOptions {
  if (process.env.LOGICWEB_LAN !== '1') return { host: '127.0.0.1', port };
  const key = resolve(__dirname, 'certs/dev-key.pem');
  const cert = resolve(__dirname, 'certs/dev-cert.pem');
  if (!existsSync(key) || !existsSync(cert)) {
    throw new Error(
      'LOGICWEB_LAN=1 needs a TLS certificate for the secure context WebUSB requires.\n' +
      'Run `npm run cert` to generate certs/dev-{key,cert}.pem, then retry.');
  }
  return {
    host: '0.0.0.0',
    port,
    https: { key: readFileSync(key), cert: readFileSync(cert) },
  };
}

/*
 * Fail the build when a run-time asset is missing, rather than shipping a bundle that
 * looks fine and 404s on first use.
 *
 * `public/pyodide/` and `public/decoders/` are gitignored - they are vendored by
 * `npm run vendor` - so a fresh clone would otherwise build something that dies on the
 * first decode with no hint as to why.
 *
 * The two licence texts are checked for the same reason, one step removed: without them
 * the build still runs perfectly, and ships MPL-2.0 and PSF code with no notice
 * attached. A silent licensing defect is worse than a loud missing file.
 */
function requireRuntimeAssets(): Plugin {
  return {
    name: 'logicweb:runtime-assets',
    apply: 'build',
    buildStart() {
      const required = [
        ['public/pyodide', 'the Pyodide runtime'],
        ['public/decoders', 'the sigrok decoder tree'],
        ['public/pyodide/LICENSE-pyodide-MPL-2.0.txt', "Pyodide's licence"],
        ['public/pyodide/LICENSE-cpython-PSF.txt', "the embedded CPython's licence"],
      ] as const;
      const missing = required
        .filter(([p]) => !existsSync(resolve(__dirname, p)))
        .map(([p, what]) => `  ${p}  (${what})`);
      if (missing.length > 0) {
        this.error(
          `the build would 404 at run time, missing:\n${missing.join('\n')}\n` +
          `Run \`npm run vendor -- <libsigrokdecode/decoders>\`.`);
      }
    },
  };
}

/*
 * Put this project's own GPLv3 text in the published tree.
 *
 * GPLv3 section 6 wants the corresponding source offered to whoever receives the object
 * code, and the banner on each chunk points at the repository - but a deployment that
 * carries the licence itself needs no argument about whether a link is enough. It also
 * covers the bundled decoders, which are GPL and ship their per-file headers inside
 * decoders.zip but not the licence body.
 */
function emitLicense(): Plugin {
  return {
    name: 'logicweb:emit-license',
    apply: 'build',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'LICENSE.txt',
        source: readFileSync(resolve(__dirname, 'LICENSE'), 'utf8'),
      });
      this.emitFile({
        type: 'asset',
        fileName: 'THIRD_PARTY_LICENSES.txt',
        source:
          'Pyodide\n=======\n\n' +
          readFileSync(resolve(__dirname, 'public/pyodide/LICENSE-pyodide-MPL-2.0.txt'), 'utf8') +
          '\n\nCPython embedded by Pyodide\n===========================\n\n' +
          readFileSync(resolve(__dirname, 'public/pyodide/LICENSE-cpython-PSF.txt'), 'utf8'),
      });
      this.emitFile({
        type: 'asset',
        fileName: 'DEPLOY.txt',
        source:
          'logicweb static distribution\n\n' +
          'index.html contains the UI, Decode Worker, Pyodide WASM/stdlib and sigrok decoders.\n' +
          'Double-click it for capture, WebUSB, protocol decoding and the Advanced USB console.\n' +
          'Node, npm and a local HTTP server are not runtime dependencies.\n' +
          'It can also be served unchanged from any static HTTPS host.\n' +
          'JavaScript source maps are included for browser debugging. Advanced contains the USB console.\n',
      });
    },
  };
}

/**
 * Keep normal hashed assets/source maps, but also inline the entry JS and CSS into
 * dist/index.html. The portable build also bundles the decode worker and all of its
 * runtime data, so the result does not perform a neighbouring file:// import or fetch.
 */
function inlineEntryForFileOpen(): Plugin {
  return {
    name: 'logicweb:inline-entry-for-file-open',
    apply: 'build',
    enforce: 'post',
    closeBundle() {
      const out = resolve(__dirname, 'dist');
      const indexPath = resolve(out, 'index.html');
      let html = readFileSync(indexPath, 'utf8');
      html = html.replace(
        /<script\s+type="module"[^>]*\ssrc="([^"]+)"[^>]*><\/script>/,
        (_tag, src: string) => {
          const rel = src.replace(/^\.\//, '').replace(/^\//, '');
          let code = readFileSync(resolve(out, rel), 'utf8');
          const dir = rel.includes('/') ? rel.slice(0, rel.lastIndexOf('/') + 1) : '';
          // Both the entry and the inline worker carry source map comments. Put the
          // maps in data URLs so moving index.html alone keeps TypeScript debugging.
          code = code.replace(
            /\/\/# sourceMappingURL=([A-Za-z0-9_./-]+\.map)/g,
            (_comment, map: string) => {
              const mapPath = resolve(
                out, dir, map.replace(/^\.\//, '').replace(/^\//, ''));
              return `//# sourceMappingURL=data:application/json;base64,${
                readFileSync(mapPath).toString('base64')}`;
            },
          );
          code = code.replace(/<\/script/gi, '<\\/script');
          return `<script type="module">\n${code}\n</script>`;
        },
      );
      html = html.replace(
        /<link\s+rel="stylesheet"[^>]*\shref="([^"]+)"[^>]*>/,
        (_tag, href: string) => {
          const rel = href.replace(/^\.\//, '').replace(/^\//, '');
          return `<style>\n${readFileSync(resolve(out, rel), 'utf8')}\n</style>`;
        },
      );
      html = html.replace(
        /<link\s+rel="icon"[^>]*>/,
        `<link rel="icon" type="image/svg+xml" href="data:image/svg+xml;base64,${
          readFileSync(resolve(out, 'favicon.svg')).toString('base64')}">`,
      );
      writeFileSync(indexPath, html);

      if (portable) {
        // All executable/runtime files and source maps are now represented inside
        // index.html. Leave only documentation/licences beside the portable app.
        for (const rel of ['assets', 'pyodide', 'decoders', 'favicon.svg', '.nojekyll']) {
          const generated = resolve(out, rel);
          if (existsSync(generated)) rmSync(generated, { recursive: true });
        }
      }
    },
  };
}

/*
 * Every source file carries an SPDX header, but the minifier strips comments, so the
 * built bundles would otherwise reach users with no licence notice at all - which is
 * the one thing the GPL is actually about. Re-attach it to each emitted chunk.
 */
const BANNER =
  '/*! SPDX-License-Identifier: GPL-3.0-or-later\n' +
  ' * logicweb - Copyright (C) 2026 Daniel Tralamazza\n' +
  ' * Free software with NO WARRANTY, under GNU GPL v3 or later.\n' +
  ' * Source: https://github.com/tralamazza/logicweb\n' +
  ' */';

const portable = process.env.LOGICWEB_PORTABLE === '1';
const portableAssets = portable ? {
  pyodideMjs: readFileSync(resolve(__dirname, 'public/pyodide/pyodide.mjs')).toString('base64'),
  pyodideAsmMjs: readFileSync(resolve(__dirname, 'public/pyodide/pyodide.asm.mjs')).toString('base64'),
  pyodideWasm: readFileSync(resolve(__dirname, 'public/pyodide/pyodide.asm.wasm')).toString('base64'),
  stdlibZip: readFileSync(resolve(__dirname, 'public/pyodide/python_stdlib.zip')).toString('base64'),
  lockJson: readFileSync(resolve(__dirname, 'public/pyodide/pyodide-lock.json')).toString('base64'),
  decodersZip: readFileSync(resolve(__dirname, 'public/decoders/decoders.zip')).toString('base64'),
} : null;

export default defineConfig({
  // Asset URLs remain portable when dist/ is hosted below a path. The entry itself is
  // inlined after build so it also works from file://.
  base: './',
  server: lanServer(5173),
  preview: lanServer(5174),

  define: {
    __LOGICWEB_PORTABLE_ASSETS__: JSON.stringify(portableAssets),
  },

  /*
   * Bundle the inline decode worker as one classic script. A file:// document's
   * opaque origin cannot start a module Blob worker in Chromium; a classic Blob
   * worker can. Vite folds the worker's static TypeScript imports into this IIFE,
   * while Pyodide's run-time blob modules continue to use dynamic import().
   */
  worker: {
    format: 'iife',
    rollupOptions: { output: { banner: BANNER } },
  },

  build: {
    // Keep production minification while making the exact TypeScript sources available
    // in DevTools when diagnosing USB/decoder issues on a user's machine.
    sourcemap: true,
    chunkSizeWarningLimit: portable ? 20_000 : 500,
    rollupOptions: { output: { banner: BANNER } },
  },

  plugins: [requireRuntimeAssets(), emitLicense(), inlineEntryForFileOpen()],
});
