#!/usr/bin/env python3
"""Generate src/decode/decoders/manifest.json from a libsigrokdecode checkout.

The shim is pure Python, so decoder metadata can be extracted with the host
interpreter at build time. That means the UI can list and configure every
decoder without loading Pyodide at all - Pyodide is only needed to actually
decode.

Usage: build-manifest.py <libsigrokdecode/decoders> <out.json>
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    dec_dir, out_path = sys.argv[1], sys.argv[2]

    sys.path.insert(0, os.path.join(HERE, '..', 'py'))
    sys.path.insert(0, dec_dir)
    import srdengine

    ids = sorted(d for d in os.listdir(dec_dir)
                 if d != 'common' and os.path.isfile(os.path.join(dec_dir, d, 'pd.py')))

    entries, failed = [], {}
    for d in ids:
        try:
            entries.append(srdengine.describe(d))
        except Exception as e:
            failed[d] = '%s: %s' % (type(e).__name__, e)

    if failed:
        # Fail loudly: a decoder that will not even describe is a bundling bug,
        # not something to silently drop from the menu.
        print('FAILED to describe %d decoder(s):' % len(failed), file=sys.stderr)
        for k, v in failed.items():
            print('  %s -> %s' % (k, v), file=sys.stderr)
        sys.exit(1)

    blob = json.dumps(entries, separators=(',', ':'), sort_keys=True)

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    # Emitted as a TypeScript module holding one JSON string literal rather
    # than a .json file: it needs no `resolveJsonModule` (tsconfig.json is
    # shared and not ours to edit), tsc parses one literal instead of a
    # 150 KB object graph, and JSON.parse beats an object literal at runtime.
    with open(out_path, 'w') as f:
        f.write('// GENERATED by src/decode/tools/build-manifest.py - do not edit.\n')
        f.write('// %d stock libsigrokdecode decoders.\n' % len(entries))
        f.write("import type { DecoderInfo } from '../types';\n\n")
        f.write('const MANIFEST_JSON = %s;\n\n' % json.dumps(blob))
        f.write('export default JSON.parse(MANIFEST_JSON) as DecoderInfo[];\n')
    print('%s: %d decoders, %d bytes' % (out_path, len(entries),
                                         os.path.getsize(out_path)))


if __name__ == '__main__':
    main()
